# Generated by Django 6.0.5 on 2026-06-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partially_cancelled', 'Partially Cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
