# Generated by Django 6.0.5 on 2026-06-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
