# Generated by Django 6.0.5 on 2026-07-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_referralcode_referralusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='max_usage',
            new_name='max_usage_per_user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_count',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='used_at',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
